### ISSUE TITLE
Issue with using tweak along with Axon

### ISSUE THREAD

**Issue by 301nav** [Baw-Appie/Notifica#2]
There seems to be an issue when using both tweaks
![DA2E3F79-58E6-4785-A862-2884F12E1904](https://user-images.githubusercontent.com/64512105/82779426-2da3af00-9e22-11ea-87f4-2a12e39cbd9b.png)
![1728D8EB-D160-4E00-A55F-4BA733AB7F2B](https://user-images.githubusercontent.com/64512105/82779427-2e3c4580-9e22-11ea-9f70-e7a4434972d3.jpeg)
as you can see there's text behind the top notification header that shouldn't be there

**Comment by ghost** [comment]
I have this bug as well and im not using Axon

**Comment by seedgrunge** [comment]
-
